### ISSUE TITLE
Cant connect VPN in IOS

### ISSUE THREAD

**Issue by rifatul-is** [Caqil/wireguard_flutter#12]
I am using the **example code** you provided but still can't run it on **IOS**, I get an error on the profile saying "**Update Required**".
I have a developer account and I created new bundle IDs for the app. The original WireGuardKit IOS package runs fine with the same bundle ID but this one doesnt.
![IMG_9785](https://github.com/Caqil/wireguard_flutter/assets/58520916/eb465fc9-308b-490f-bbf9-7eeeb58463db)

**Comment by Caqil** [comment]
hello, what iOS do you use? minimum iOS is 15

**Comment by rifatul-is** [comment]
I am using IOS 17.0.1

**Comment by aakashch0179** [comment]
The same problem I am using IOS 17, I get an error on the profile saying "Update Required".

**Comment by mahevstark** [comment]
I am using IOS 15.8, getting same error. @Caqil 
@rifatul-is found any solution?

**Comment by Caqil** [comment]
> The same problem I am using IOS 17, I get an error on the profile saying "Update Required".



> I am using IOS 15.8, getting same error. @Caqil @rifatul-is found any solution?

hello, can you send your conf wg?

**Comment by mahevstark** [comment]
@Caqil  
it is working on android but not on ios
```

[Interface]
PrivateKey = ${response?.privateKey}
Address = ${response?.address}
DNS = ${response?.dns}


[Peer]
PublicKey = ${response?.publicKey}
AllowedIPs = ${response?.allowedIps}
PersistentKeepalive = 0
Endpoint = ${response?.endPoint}
```

**Comment by bdlukaa** [comment]
Does deleting the tunnels (profiles) and creating them again work?

If not, can you try [this solution](https://developer.apple.com/forums/thread/109780?answerId=741961022#741961022) and tell if it works?

If none of these work, please share a reproducible snippet of code for us to test. Thanks

**Comment by rifatul-is** [comment]
This is wg cofig @Caqil 

[Interface]
PrivateKey = ${response?.privateKey}
Address = ${response?.address}
DNS = ${response?.dns}

[Peer]
PublicKey = ${response?.publicKey}
AllowedIPs = ${response?.allowedIps}
Endpoint = ${response?.endPoint}

Deleting the tunnels and recreating it doesn't work.

Also this [solution](https://developer.apple.com/forums/thread/109780?answerId=741961022#741961022) doesnt work.
To reproduce the problem u can just copy the example code on a new flutter project and run on ios and it wont connect.
I was able to run the example provided in the package though.

**Comment by bdlukaa** [comment]
You need to set the `providerBundleIdentifier` according to the app bundle identifier.

* https://github.com/Caqil/wireguard_flutter/blob/d600165e9cc2885a2a03915e674c7365e7c742d2/example/lib/main.dart#L60
* https://github.com/Caqil/wireguard_flutter/blob/d600165e9cc2885a2a03915e674c7365e7c742d2/example/ios/Runner.xcodeproj/project.pbxproj#L787

**Comment by Forever921** [comment]
> You need to set the `providerBundleIdentifier` according to the app bundle identifier.
> 
> * https://github.com/Caqil/wireguard_flutter/blob/d600165e9cc2885a2a03915e674c7365e7c742d2/example/lib/main.dart#L60
> * https://github.com/Caqil/wireguard_flutter/blob/d600165e9cc2885a2a03915e674c7365e7c742d2/example/ios/Runner.xcodeproj/project.pbxproj#L787

Modified macos will work, ios will not。

**Comment by Forever921** [comment]
> > You need to set the `providerBundleIdentifier` according to the app bundle identifier.
> > 
> > * https://github.com/Caqil/wireguard_flutter/blob/d600165e9cc2885a2a03915e674c7365e7c742d2/example/lib/main.dart#L60
> > * https://github.com/Caqil/wireguard_flutter/blob/d600165e9cc2885a2a03915e674c7365e7c742d2/example/ios/Runner.xcodeproj/project.pbxproj#L787
> 
> Modified macos will work, ios will not。

I modified General->Minimun Deployments ->ios 15 can work normally 。

**Comment by bdlukaa** [comment]
Believe we need to add iOS installation instructions to the README.

**Comment by rifatul-is** [comment]
@bdlukaa @mahevstark  @aakashch0179
It does need a better IOS installation documentation. 
If you still coundn't get it to work, can you try this?

1. Add Network Extension and WireguardGoBridge to the Targets.
2. Select Runner go to Build Phase and expand Embed Foundation Extension and unckeck Copy only when installing
3. If this creates a cycle error in xcode put Embed Foundation Extension above Embed Frameworks

Hope This Helps.

**Comment by imasif** [comment]
@rifatul-is Can you check this? I am also facing the same problem: https://github.com/Caqil/wireguard_flutter/issues/27

**Comment by imasif** [comment]
```
flutter: status changed VpnStage.disconnected
flutter: failed to initialize: PlatformException(-4, Optional(Error Domain=NEVPNErrorDomain Code=5 "IPC failed" UserInfo={NSLocalizedDescription=IPC failed}), IPC failed, null)
flutter: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
flutter: #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
flutter: <asynchronous suspension>
flutter: #2      _MyAppState.initialize (package:wireguard_dart_example/main.dart:52:7)
flutter: <asynchronous suspension>
flutter:
```

getting this error, when click on the initialize button on IOS, is this because I am using a Simulator? @Caqil @rifatul-is

**Comment by robbysneller** [comment]
@imasif Im not sure of this exact error but I do believe that network extensions do not work on the iOS simulator

https://forums.developer.apple.com/forums/thread/101663

**Comment by imasif** [comment]
I am using ios 15.8.3
but I get the following
<img width="915" alt="Screenshot 2024-10-25 at 2 43 14 AM" src="https://github.com/user-attachments/assets/4c7162cf-44ca-4546-851f-72d9b9b83e9d">


This is my VPN Config what the example app show:
![WhatsApp Image 2024-10-25 at 03 04 16](https://github.com/user-attachments/assets/481ea587-c3c4-4fe7-81e9-a2441916d7e9)


how to resolve this? Same config of wireguard works with Wireguard app

**Comment by bdlukaa** [comment]
@imasif make sure to provide `providerBundleIdentifier` in your `startVpn` function call, and make sure that bundle identifier is the same as your app's bundle identifier.

Then, uninstall the app and run it on release mode. Thanks.

**Comment by imasif** [comment]
@bdlukaa This is same, still not connecting!

**Comment by imasif** [comment]
@bdlukaa This is same, I also did as you said `flutter run --release` still no connecting!

**Comment by imasif** [comment]
@bdlukaa If I dont delete the following under the red box this new issue arises:
<img width="1334" alt="Screenshot 2024-10-26 at 2 46 57 AM" src="https://github.com/user-attachments/assets/5c2ab824-a06e-4ae2-8dbb-3e806d9c5d9a">

I deleted them, in the red box then the issue disappears is there any work around?

**Comment by imasif** [comment]
@bdlukaa @Caqil now The problem with the vpn is gone but, there is no wireguard related code, I tried copying that, it says WireguardKitGo and WireguardKitC is not found!
![WhatsApp Image 2024-10-27 at 22 47 15](https://github.com/user-attachments/assets/e5baf3b0-2327-4340-868a-40bed668d726)
<img width="1319" alt="Screenshot 2024-10-27 at 10 48 16 PM" src="https://github.com/user-attachments/assets/d785848b-c0d8-47ac-9c62-809cd5cb1325">

**Comment by Logoutbye** [comment]
@imasif did you solved it?
