### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by robbysneller** [Caqil/wireguard_flutter#19]
Does this work on MacOS? 

I have been trying to get the project in the `example` directory working for some time and I have had no luck. I have renamed and double checked the bundle identifiers throughout the project and entitlements and they seem to be fine. I changed the path for the external build tool to my own downloaded copy of wireguard-apple sources vs the hardcoded path. and even tried recreating the WGExtension as a system extension vs an app extension after reading that could be an issue. It is still not working.

I can build the app and initialize "successfully" but I am just getting logs like this every time I try and connect where it does nothing and there is no error output. I am able to connect to the wireguard server using the macOS client without issue.

```
flutter: status changed VpnStage.disconnected
2024-03-14 14:48:34.798 example_flutter[49429:4784548] Starting the tunnel
flutter: status changed VpnStage.connecting
flutter: status changed VpnStage.connecting
flutter: status changed VpnStage.disconnected
flutter: status changed VpnStage.disconnected
```

I added an override to the init of the PacketTunnelProvider to log when it is initialized and it never prints so I am thinking that is my issue but I'm not sure how to deal with that.

I am very new to macOS/iOS development so if I am missing some basic setup steps that are not mentioned in the readme or wireguard-apple repo, please let me know

**Comment by SudipZluck** [comment]
> Does this work on MacOS?
> 
> I have been trying to get the project in the `example` directory working for some time and I have had no luck. I have renamed and double checked the bundle identifiers throughout the project and entitlements and they seem to be fine. I changed the path for the external build tool to my own downloaded copy of wireguard-apple sources vs the hardcoded path. and even tried recreating the WGExtension as a system extension vs an app extension after reading that could be an issue. It is still not working.
> 
> I can build the app and initialize "successfully" but I am just getting logs like this every time I try and connect where it does nothing and there is no error output. I am able to connect to the wireguard server using the macOS client without issue.
> 
> ```
> flutter: status changed VpnStage.disconnected
> 2024-03-14 14:48:34.798 example_flutter[49429:4784548] Starting the tunnel
> flutter: status changed VpnStage.connecting
> flutter: status changed VpnStage.connecting
> flutter: status changed VpnStage.disconnected
> flutter: status changed VpnStage.disconnected
> ```
> 
> I added an override to the init of the PacketTunnelProvider to log when it is initialized and it never prints so I am thinking that is my issue but I'm not sure how to deal with that.
> 
> I am very new to macOS/iOS development so if I am missing some basic setup steps that are not mentioned in the readme or wireguard-apple repo, please let me know

Same issue

**Comment by Caqil** [comment]
please double check providerBundleIdentifier same like in xcode extension

**Comment by cmaxdev** [comment]
Hi, @robbysneller, I met same issue using this flutter package.
I installed this package and working good for android but it is not working for macos and ios.
I checked macos directory but I can not see any WGExtension folder at there.
![image](https://github.com/Caqil/wireguard_flutter/assets/118275356/fe038dbf-2513-4125-a1d3-6f6f67581840)

Does it need to add manually? Thanks for your suuport.

**Comment by robbysneller** [comment]
yes, sorry I should have made this more clear in my comment. I was explaining how to get the example macOS/iOS app in the repository working. if you are integrating it into your own, you will need to create the external build system target and the wireguard extension target yourself. I figured this out by opening the example and trying to set it up the same way in my own project

**Comment by robbysneller** [comment]
when integrating into your own project you will need to add the extension, the build system, the same capabilities under the signing and capabilities section of the runner and extension target (equivalent to permissions on android) as the example project, add the package dependency for the passepartoutvpn/wireguard-apple under the Runner project and then add the WireGuardKit framework under your new extension and runner target in Xcode. 

Sorry if I forgot any steps but like I said, I would suggest cloning the wireguard_flutter repo and opening the macOS project under the example folder and then try and copy the configuration when working with your own project. 

If you are unfamiliar with Xcode and Mac/iOS development like I am, it may be a painful process, but I can promise you it will work if you set it up right! good luck!

**Comment by robbysneller** [comment]
sorry for the spam of comments, but to be even more clear, this library will NOT work out of the box for iOS/macOS as it does for android. there are many manual steps you must take in Xcode to get things working after adding the flutter dependency to your existing project. I suspect based on all these issues that many flutter devs like me are not very familiar with traditional iOS/macOS development and thus it is confusing when things do not work right away as it does in android.

I have documented some of the steps here in this thread but I am not promising the instructions are complete. I messed with this for quite a while to get it working and tried many things. Maybe one day if I have time and there are still no updated instructions, I will start from scratch and document all of the steps needed to get it working and submit a pull request with the example. 

Until then, I would suggest for anyone wanting to integrate into their own app to clone the example and have it open in Xcode side by side with your own project and update your own project until the configuration matches. These are all things I wish I had known weeks ago so hopefully you will find it helpful

**Comment by cmaxdev** [comment]
Hi, @robbysneller
I did all but It is not working yet. I just checked my PacketTunnelProvider.swift in WGExtension and example's file but It is different.
It means not compiled correctly yet?
Thank you

**Comment by robbysneller** [comment]
@cmaxdev hi, sorry for the late response. yes, you will need to manually copy the code in PacketTunnelProvider.swift from the example

**Comment by SpaceXM** [comment]
i have a strange issue with this, i can run and build all from VS code with flutter run/build macos but i cannot build the app using Xcode, using just vs code i'm able to run the app and the tunnel is completely working

the error output from Xcode is:

make: *** [/Users/test/Library/Developer/Xcode/DerivedData/Runner-haoarerbfrgaeaflntisbxzkvalk/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release/wireguard-go-bridge/goroot/.prepared] Error 1
Command ExternalBuildToolExecution failed with a nonzero exit code

**Comment by talkbiz** [comment]
> @talkbiz did you follow the other steps to download the wireguard sources, and add the package dependency for WireGuardKit? it seems like you may have missed some steps.
> 
> @SpaceXM I have the same issue. my app will not run in Xcode but I am able to run it in the terminal. not sure why, but I haven't tried to trouble shoot it since I don't really have a need to run the app in Xcode. but you are not alone :)

Thanks, I’ve been able to fix it by calmly going through your messages again.

**Comment by SpaceXM** [comment]
Yes i can confirm that is possibile to run the package using Xcode, Unfortunately, I had to drop VPN support in my app due to Apple's strict rules for individual developers not allowing the use of VPNs in any way

**Comment by VamshiKrishnaM13** [comment]
@robbysneller @Caqil 
I have followed all the instructions provided, but still getting issue in macos.
<img width="1440" alt="Screenshot 2024-09-06 at 5 30 38 PM" src="https://github.com/user-attachments/assets/b7653785-bc44-4bb7-9243-dc67720e426a">

**Comment by SudipZluck** [comment]
> @robbysneller @Caqil I have followed all the instructions provided, but still getting issue in macos. <img alt="Screenshot 2024-09-06 at 5 30 38 PM" width="1440" src="https://private-user-images.githubusercontent.com/145459431/365156047-b7653785-bc44-4bb7-9243-dc67720e426a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2OTI2MDYsIm5iZiI6MTcyNTY5MjMwNiwicGF0aCI6Ii8xNDU0NTk0MzEvMzY1MTU2MDQ3LWI3NjUzNzg1LWJjNDQtNGJiNy05MjQzLWRjNjc3MjBlNDI2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QwNjU4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmEyYzc5MTBmOGJlNGRkOTM2MDU5ZWVlNTBmMTE4N2Q0ZGEwYzkzMGVjNDRkZjdhY2E4MDRhZDdhNWZkYmU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OEzrtQXwCH_bS2mtTHmTjK7w1HwOCiw-vEgJUmn8gVA">

//
//  PacketTunnelProvider.swift
//  WireGuardNetworkExtension
//
//  Created by Alexandr Ruban on 05.10.2023.
//

// SPDX-License-Identifier: MIT
// Copyright © 2018-2023 WireGuard LLC. All Rights Reserved.

// SPDX-License-Identifier: MIT
// Copyright © 2018-2023 WireGuard LLC. All Rights Reserved.

import Foundation
import NetworkExtension
import WireGuardKit


enum PacketTunnelProviderError: String, Error {
    case invalidProtocolConfiguration
    case cantParseWgQuickConfig
}


extension String {

    func splitToArray(separator: Character = ",", trimmingCharacters: CharacterSet? = nil) -> [String] {
        return split(separator: separator)
            .map {
                if let charSet = trimmingCharacters {
                    return $0.trimmingCharacters(in: charSet)
                } else {
                    return String($0)
                }
        }
    }

}


extension Optional where Wrapped == String {

    func splitToArray(separator: Character = ",", trimmingCharacters: CharacterSet? = nil) -> [String] {
        switch self {
        case .none:
            return []
        case .some(let wrapped):
            return wrapped.splitToArray(separator: separator, trimmingCharacters: trimmingCharacters)
        }
    }

}


extension TunnelConfiguration {

    enum ParserState {
        case inInterfaceSection
        case inPeerSection
        case notInASection
    }

    enum ParseError: Error {
        case invalidLine(String.SubSequence)
        case noInterface
        case multipleInterfaces
        case interfaceHasNoPrivateKey
        case interfaceHasInvalidPrivateKey(String)
        case interfaceHasInvalidListenPort(String)
        case interfaceHasInvalidAddress(String)
        case interfaceHasInvalidDNS(String)
        case interfaceHasInvalidMTU(String)
        case interfaceHasUnrecognizedKey(String)
        case peerHasNoPublicKey
        case peerHasInvalidPublicKey(String)
        case peerHasInvalidPreSharedKey(String)
        case peerHasInvalidAllowedIP(String)
        case peerHasInvalidEndpoint(String)
        case peerHasInvalidPersistentKeepAlive(String)
        case peerHasInvalidTransferBytes(String)
        case peerHasInvalidLastHandshakeTime(String)
        case peerHasUnrecognizedKey(String)
        case multiplePeersWithSamePublicKey
        case multipleEntriesForKey(String)
    }

    convenience init(fromWgQuickConfig wgQuickConfig: String, called name: String? = nil) throws {
        var interfaceConfiguration: InterfaceConfiguration?
        var peerConfigurations = [PeerConfiguration]()

        let lines = wgQuickConfig.split { $0.isNewline }

        var parserState = ParserState.notInASection
        var attributes = [String: String]()

        for (lineIndex, line) in lines.enumerated() {
            var trimmedLine: String
            if let commentRange = line.range(of: "#") {
                trimmedLine = String(line[..<commentRange.lowerBound])
            } else {
                trimmedLine = String(line)
            }

            trimmedLine = trimmedLine.trimmingCharacters(in: .whitespacesAndNewlines)
            let lowercasedLine = trimmedLine.lowercased()

            if !trimmedLine.isEmpty {
                if let equalsIndex = trimmedLine.firstIndex(of: "=") {
                    // Line contains an attribute
                    let keyWithCase = trimmedLine[..<equalsIndex].trimmingCharacters(in: .whitespacesAndNewlines)
                    let key = keyWithCase.lowercased()
                    let value = trimmedLine[trimmedLine.index(equalsIndex, offsetBy: 1)...].trimmingCharacters(in: .whitespacesAndNewlines)
                    let keysWithMultipleEntriesAllowed: Set<String> = ["address", "allowedips", "dns"]
                    if let presentValue = attributes[key] {
                        if keysWithMultipleEntriesAllowed.contains(key) {
                            attributes[key] = presentValue + "," + value
                        } else {
                            throw ParseError.multipleEntriesForKey(keyWithCase)
                        }
                    } else {
                        attributes[key] = value
                    }
                    let interfaceSectionKeys: Set<String> = ["privatekey", "listenport", "address", "dns", "mtu"]
                    let peerSectionKeys: Set<String> = ["publickey", "presharedkey", "allowedips", "endpoint", "persistentkeepalive"]
                    if parserState == .inInterfaceSection {
                        guard interfaceSectionKeys.contains(key) else {
                            throw ParseError.interfaceHasUnrecognizedKey(keyWithCase)
                        }
                    } else if parserState == .inPeerSection {
                        guard peerSectionKeys.contains(key) else {
                            throw ParseError.peerHasUnrecognizedKey(keyWithCase)
                        }
                    }
                } else if lowercasedLine != "[interface]" && lowercasedLine != "[peer]" {
                    throw ParseError.invalidLine(line)
                }
            }

            let isLastLine = lineIndex == lines.count - 1

            if isLastLine || lowercasedLine == "[interface]" || lowercasedLine == "[peer]" {
                // Previous section has ended; process the attributes collected so far
                if parserState == .inInterfaceSection {
                    let interface = try TunnelConfiguration.collate(interfaceAttributes: attributes)
                    guard interfaceConfiguration == nil else { throw ParseError.multipleInterfaces }
                    interfaceConfiguration = interface
                } else if parserState == .inPeerSection {
                    let peer = try TunnelConfiguration.collate(peerAttributes: attributes)
                    peerConfigurations.append(peer)
                }
            }

            if lowercasedLine == "[interface]" {
                parserState = .inInterfaceSection
                attributes.removeAll()
            } else if lowercasedLine == "[peer]" {
                parserState = .inPeerSection
                attributes.removeAll()
            }
        }

        let peerPublicKeysArray = peerConfigurations.map { $0.publicKey }
        let peerPublicKeysSet = Set<PublicKey>(peerPublicKeysArray)
        if peerPublicKeysArray.count != peerPublicKeysSet.count {
            throw ParseError.multiplePeersWithSamePublicKey
        }

        if let interfaceConfiguration = interfaceConfiguration {
            self.init(name: name, interface: interfaceConfiguration, peers: peerConfigurations)
        } else {
            throw ParseError.noInterface
        }
    }

    func asWgQuickConfig() -> String {
        var output = "[Interface]\n"
        output.append("PrivateKey = \(interface.privateKey.base64Key)\n")
        if let listenPort = interface.listenPort {
            output.append("ListenPort = \(listenPort)\n")
        }
        if !interface.addresses.isEmpty {
            let addressString = interface.addresses.map { $0.stringRepresentation }.joined(separator: ", ")
            output.append("Address = \(addressString)\n")
        }
        if !interface.dns.isEmpty || !interface.dnsSearch.isEmpty {
            var dnsLine = interface.dns.map { $0.stringRepresentation }
            dnsLine.append(contentsOf: interface.dnsSearch)
            let dnsString = dnsLine.joined(separator: ", ")
            output.append("DNS = \(dnsString)\n")
        }
        if let mtu = interface.mtu {
            output.append("MTU = \(mtu)\n")
        }

        for peer in peers {
            output.append("\n[Peer]\n")
            output.append("PublicKey = \(peer.publicKey.base64Key)\n")
            if let preSharedKey = peer.preSharedKey?.base64Key {
                output.append("PresharedKey = \(preSharedKey)\n")
            }
            if !peer.allowedIPs.isEmpty {
                let allowedIPsString = peer.allowedIPs.map { $0.stringRepresentation }.joined(separator: ", ")
                output.append("AllowedIPs = \(allowedIPsString)\n")
            }
            if let endpoint = peer.endpoint {
                output.append("Endpoint = \(endpoint.stringRepresentation)\n")
            }
            if let persistentKeepAlive = peer.persistentKeepAlive {
                output.append("PersistentKeepalive = \(persistentKeepAlive)\n")
            }
        }

        return output
    }

    private static func collate(interfaceAttributes attributes: [String: String]) throws -> InterfaceConfiguration {
        guard let privateKeyString = attributes["privatekey"] else {
            throw ParseError.interfaceHasNoPrivateKey
        }
        guard let privateKey = PrivateKey(base64Key: privateKeyString) else {
            throw ParseError.interfaceHasInvalidPrivateKey(privateKeyString)
        }
        var interface = InterfaceConfiguration(privateKey: privateKey)
        if let listenPortString = attributes["listenport"] {
            guard let listenPort = UInt16(listenPortString) else {
                throw ParseError.interfaceHasInvalidListenPort(listenPortString)
            }
            interface.listenPort = listenPort
        }
        if let addressesString = attributes["address"] {
            var addresses = [IPAddressRange]()
            for addressString in addressesString.splitToArray(trimmingCharacters: .whitespacesAndNewlines) {
                guard let address = IPAddressRange(from: addressString) else {
                    throw ParseError.interfaceHasInvalidAddress(addressString)
                }
                addresses.append(address)
            }
            interface.addresses = addresses
        }
        if let dnsString = attributes["dns"] {
            var dnsServers = [DNSServer]()
            var dnsSearch = [String]()
            for dnsServerString in dnsString.splitToArray(trimmingCharacters: .whitespacesAndNewlines) {
                if let dnsServer = DNSServer(from: dnsServerString) {
                    dnsServers.append(dnsServer)
                } else {
                    dnsSearch.append(dnsServerString)
                }
            }
            interface.dns = dnsServers
            interface.dnsSearch = dnsSearch
        }
        if let mtuString = attributes["mtu"] {
            guard let mtu = UInt16(mtuString) else {
                throw ParseError.interfaceHasInvalidMTU(mtuString)
            }
            interface.mtu = mtu
        }
        return interface
    }

    private static func collate(peerAttributes attributes: [String: String]) throws -> PeerConfiguration {
        guard let publicKeyString = attributes["publickey"] else {
            throw ParseError.peerHasNoPublicKey
        }
        guard let publicKey = PublicKey(base64Key: publicKeyString) else {
            throw ParseError.peerHasInvalidPublicKey(publicKeyString)
        }
        var peer = PeerConfiguration(publicKey: publicKey)
        if let preSharedKeyString = attributes["presharedkey"] {
            guard let preSharedKey = PreSharedKey(base64Key: preSharedKeyString) else {
                throw ParseError.peerHasInvalidPreSharedKey(preSharedKeyString)
            }
            peer.preSharedKey = preSharedKey
        }
        if let allowedIPsString = attributes["allowedips"] {
            var allowedIPs = [IPAddressRange]()
            for allowedIPString in allowedIPsString.splitToArray(trimmingCharacters: .whitespacesAndNewlines) {
                guard let allowedIP = IPAddressRange(from: allowedIPString) else {
                    throw ParseError.peerHasInvalidAllowedIP(allowedIPString)
                }
                allowedIPs.append(allowedIP)
            }
            peer.allowedIPs = allowedIPs
        }
        if let endpointString = attributes["endpoint"] {
            guard let endpoint = Endpoint(from: endpointString) else {
                throw ParseError.peerHasInvalidEndpoint(endpointString)
            }
            peer.endpoint = endpoint
        }
        if let persistentKeepAliveString = attributes["persistentkeepalive"] {
            guard let persistentKeepAlive = UInt16(persistentKeepAliveString) else {
                throw ParseError.peerHasInvalidPersistentKeepAlive(persistentKeepAliveString)
            }
            peer.persistentKeepAlive = persistentKeepAlive
        }
        return peer
    }

}



class PacketTunnelProvider: NEPacketTunnelProvider {

    private lazy var adapter: WireGuardAdapter = {
        return WireGuardAdapter(with: self) { [weak self] _, message in
            self?.log(message)
        }
    }()

    func log(_ message: String) {
        NSLog("WireGuard Tunnel: %@\n", message)
    }

    override func startTunnel(options: [String : NSObject]?, completionHandler: @escaping (Error?) -> Void) {
        log("Starting tunnel")
        print("Hjiji")
        log("zszszs")
        guard let protocolConfiguration = self.protocolConfiguration as? NETunnelProviderProtocol,
              let providerConfiguration = protocolConfiguration.providerConfiguration,
              let wgQuickConfig = providerConfiguration["wgQuickConfig"] as? String else {
            log("Invalid provider configuration")
            completionHandler(PacketTunnelProviderError.invalidProtocolConfiguration)
            return
        }
        
        log("wg-quick config parseable")
        guard let tunnelConfiguration = try? TunnelConfiguration(fromWgQuickConfig: wgQuickConfig) else {
            log("wg-quick config not parseable")
            completionHandler(PacketTunnelProviderError.cantParseWgQuickConfig)
            return
        }
        
        log("adapter.start")
        adapter.start(tunnelConfiguration: tunnelConfiguration) { [weak self] adapterError in
            guard let self = self else { return }
            if let adapterError = adapterError {
                self.log("WireGuard adapter error: \(adapterError.localizedDescription)")
            } else {
                let interfaceName = self.adapter.interfaceName ?? "unknown"
                self.log("Tunnel interface is \(interfaceName)")
            }
            completionHandler(adapterError)
        }
    }

    override func stopTunnel(with reason: NEProviderStopReason, completionHandler: @escaping () -> Void) {
        log("Stopping tunnel")
        adapter.stop { [weak self] error in
            guard let self = self else { return }
            if let error = error {
                self.log("Failed to stop WireGuard adapter: \(error.localizedDescription)")
            }
            completionHandler()

            #if os(macOS)
            // HACK: We have to kill the tunnel process ourselves because of a macOS bug
            exit(0)
            #endif
        }
    }

    override func handleAppMessage(_ messageData: Data, completionHandler: ((Data?) -> Void)?) {
        guard let completionHandler = completionHandler else { return }

        if messageData.count == 1 && messageData[0] == 0 {
            adapter.getRuntimeConfiguration { settings in
                var data: Data?
                if let settings = settings {
                    data = settings.data(using: .utf8)!
                }
                completionHandler(data)
            }
        } else {
            completionHandler(nil)
        }
    }

    override func sleep(completionHandler: @escaping () -> Void) {
        // Add code here to get ready to sleep.
        completionHandler()
    }

    override func wake() {
        // Add code here to wake up.
    }
}

Can you copy all this and paste it on PacketTunnelProvider then try again

**Comment by VamshiKrishnaM13** [comment]
```
A Dart VM Service on macOS is available at: http://127.0.0.1:52060/nrde4rbFzEM=/
flutter: status changed VpnStage.disconnected
flutter: status changed VpnStage.disconnected
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:52060/nrde4rbFzEM=/
2024-09-07 13:47:08.750 Osto Access[81448:1570715] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.

flutter: status changed VpnStage.disconnected
flutter: initialize success my_wg_vpn

flutter: status changed VpnStage.disconnected
2024-09-07 13:47:17.504 Osto Access[81448:1570715] Starting the tunnel
flutter: status changed VpnStage.connecting
flutter: status changed VpnStage.connecting
flutter: status changed VpnStage.connecting
flutter: status changed VpnStage.connected
flutter: status changed VpnStage.connected
flutter: status changed VpnStage.connected

flutter: getting stage
flutter: stage: VpnStage.connected
```

@SudipZluck Thanks for sharing this, built successfully & connected to server but then internet is not working & how to get those stats. UI for stats is available, but I think there is no backend for stats in mac. can you please help with this?

**Comment by imasif** [comment]
@VamshiKrishnaM13 @bdlukaa @Caqil  I used the same code, the app runs, vpn get created on ios but cannot connect. I am using IOS 15.8.3 Iphone SE 1st edition. What can I do? Trying to run the example app!
<img width="1156" alt="Screenshot 2024-10-30 at 4 31 19 AM" src="https://github.com/user-attachments/assets/58196b67-1e76-4ccd-80e0-d4e90ed0f619">

**Comment by bdlukaa** [comment]
Make sure to not use the emulator and use the release mode.

**Comment by imasif** [comment]
Yes did the same, Real device and in release mode there is no debug info, tested that as well! not able to connect to vpn.
