### ISSUE TITLE
Windows vpn is not connecting

### ISSUE THREAD

**Issue by aakashch0179** [Caqil/wireguard_flutter#23]
I try to debug in windows and its successfully debug then i press connect button its throw this error please help me.

```
Starting service with command line: D:\Codecaneone Projects\wireguard\build\windows\x64\runner\Debug\wireguard_svc.exe -service -config-file="C:\Users\cheta\AppData\Local\Temp\wg_12FA.tmp.conf"
flutter: status is changed VpnStage.preparing
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Missing extension byte (at offset 1)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1748:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:356:42)
#2      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:502:29)
#3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477:12)
#4      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:646:44)
#5      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
```

**Comment by aakashch0179** [comment]
> did you add wireguard conf?

yes i add conf file

**Comment by Caqil** [comment]
> > did you add wireguard conf?
> 
> yes i add conf

You need run as administrator for vcode.

**Comment by aakashch0179** [comment]
> > > did you add wireguard conf?
> > 
> > 
> > yes i add conf
> 
> You need run as administrator for vcode.

ok i can try

**Comment by evangelme** [comment]
i had the same problem i do not why but i changed the conf name 
name = 'my_wg_vpn'
to something else and it worked do the same it should work

**Comment by aakashch0179** [comment]
> i had the same problem i do not why but i changed the conf name name = 'my_wg_vpn' to something else and it worked do the same it should work if it dose not give me the conf file and i check it for you

Sir after connecting your windows ip is changing or not, I connected successfully in windows and ip is not changeing

**Comment by VamshiKrishnaM13** [comment]
![image](https://github.com/user-attachments/assets/7aa52e34-f088-4159-b9b7-b0199fa293f5)

Am i missing something or is there any issue?

**Comment by VamshiKrishnaM13** [comment]
@aakashch0179 @evangelme @Caqil 
It still has the same issue, My VPN is not even in a connected state for at least once. After connecting state, it is directly moving to the disconnected state with the above issue as shared in the image. I have even tried renaming my_wg_vpn name as well.
Please help.
