### ISSUE TITLE
Vpn not connecting in iOS

### ISSUE THREAD

**Issue by HassanFlutterDev** [Caqil/wireguard_flutter#26]
Whenever i click on connect its shows connecting then shows disconnected it not connecting can you help me or give me any demo of config or address to make me easy to test it
<img width="876" alt="Screenshot 2024-04-14 at 10 39 39 PM" src="https://github.com/Caqil/wireguard_flutter/assets/107813827/fef81482-a990-4207-a3cc-ba172cbf532f">

**Comment by KavinduDissanayake** [comment]
Same issue I got !!!


![Screenshot 2024-05-09 at 12 31 33](https://github.com/Caqil/wireguard_flutter/assets/51842810/e1b2f937-0c4d-47c9-bdf4-40f32a7a139b)

**Comment by robbysneller** [comment]
hey, I was having these exact same issues a few weeks ago and finally got the time to write up my solution. I just posted some steps I took to get it working. hopefully you will both find it helpful 

https://github.com/Caqil/wireguard_flutter/issues/19#issuecomment-2102749919

**Comment by HassanFlutterDev** [comment]
> hey, I was having these exact same issues a few weeks ago and finally got the time to write up my solution. I just posted some steps I took to get it working. hopefully you will both find it helpful
> 
> [#19 (comment)](https://github.com/Caqil/wireguard_flutter/issues/19#issuecomment-2102749919)

Thanks i got fixed it by reinstalling example project and re configure it properly and also change wireguard_flutter ver to latest then i got my vpn fixed

**Comment by evangelme** [comment]
@HassanFlutterDev how did you fix it? it stuck in connecting in macos and in iphone it says update require in vpn settings...
my email address is atavakolpour@gmail.com i think you r from iran if yes i willing to play you to solve my problem because i really need this...
can you tell me what did you exactly do?

**Comment by HassanFlutterDev** [comment]
i mailed you check your mail


> @HassanFlutterDev how did you fix it? it stuck in connecting in macos and in iphone it says update require in vpn settings... my email address is [atavakolpour@gmail.com](mailto:atavakolpour@gmail.com) i think you r from iran if yes i willing to play you to solve my problem because i really need this... can you tell me what did you exactly do?

**Comment by evangelme** [comment]
i send you an email address and my telegram id is atavakolpour aswell i want to solve my problem if you help me i am willing to discuss what i could do to please you tnx

**Comment by imasif** [comment]
@HassanFlutterDev I am also stuck on vpn not connecting, on ios. I am willing to pay you, if you get this fixed, contact me: imasif1010@gmail.com, thanks
