### ISSUE TITLE
iOS: "AppName" must be updated by the developer before "VpnName" can be connected

### ISSUE THREAD

**Issue by 33885222** [Caqil/wireguard_flutter#30]
I built an app for iOS, and the build and launch process goes smoothly. However, the VPN does not connect because in the iPhone settings, next to the VPN profile, it says 'Update Required' and 'VPN: "AppName" must be updated by the developer before "VpnName" can be connected.' What exactly needs to be updated and how can I fix this problem?

![6e850544-6d37-4ac1-ab09-1552f725460f](https://github.com/Caqil/wireguard_flutter/assets/7829523/1bd9c5c1-2dbe-4ed0-a7e7-a48bb96634a1)

**Comment by sanburnn** [comment]
@33885222 i got some problem too. @Caqil

**Comment by Yaseendev** [comment]
Update the minimum ios deployment version of the extension to be the same as runner's minimum ios deployment
