### ISSUE TITLE
How can I fix this problem on iOS?

### ISSUE THREAD

**Issue by dreampioneer** [Caqil/wireguard_flutter#32]
![image](https://github.com/Caqil/wireguard_flutter/assets/143971762/4fec57bb-7e8f-4e61-9240-25ce8fd717e4)

I am not sure what caused this issue.
And I need your help. Please help me with your professionality.
Thanks.

**Comment by chnbrs** [comment]
Same here

**Comment by dreampioneer** [comment]
I have fixed this.
Because I can not test the VPN feature on simulations. For this, we need to use the real phones.
And I did and the VPN feature is working on iOS.
Thanks.
