### ISSUE TITLE
Failed to build iOS app

### ISSUE THREAD

**Issue by pevghenii** [Caqil/wireguard_flutter#37]
Error (Xcode): unable to spawn process '/usr/bin/make' (No such file or directory)
Although: 
"which make
/usr/bin/make"

**Comment by Caqil** [comment]
download wireguard-apple
https://github.com/WireGuard/wireguard-apple and change external library directory
![wg](https://github.com/user-attachments/assets/de1fce9f-4392-43e8-bcee-06b86525bff9)

**Comment by imasif** [comment]
@Caqil Now I am getting the following issue:
```
Uncategorized (Xcode): Command ExternalBuildToolExecution failed with a nonzero exit code
```

**Comment by imasif** [comment]
@Caqil  Can you check this? I am also facing the same problem:
https://github.com/Caqil/wireguard_flutter/issues/27
