### ISSUE TITLE
App Distribution Issue: Unable to Initiate VPN Connection

### ISSUE THREAD

**Issue by ralexy** [Caqil/wireguard_flutter#40]
Hello everyone,

I'm reaching out today with a simple issue: I can launch the app on the Mac where I compiled it. However, when I share the app on another Mac, I cannot initiate a VPN connection.

I have an individual developer license for $99. I'd like to know if the problem is related to the license, and if I need to pay for an enterprise license at $500 to be able to distribute the app on iOS and macOS?

Thank you in advance for your help!

**Comment by Caqil** [comment]
You need organization account for upload vpn apps

**Comment by ralexy** [comment]
Thanks Caqil
